# Generated by Django 5.0.4 on 2024-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='regdata',
            new_name='regdate',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='regdata',
            new_name='regdate',
        ),
    ]
